#!/bin/bash

### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the iptables based firewall
# Description:       Create iptables based firewall rules. All rules can be created using
#                     configuration files without iptables specific knowledge
### END INIT INFO

########################################################
#
# firewall
# init script for solowall-iptables
# solowall-iptables (c) Torsten Mueller 2014
# 
########################################################


IPTABLES=/sbin/iptables

case "$1" in
    start)
        source /usr/local/bin/firewall/conf/options.conf #
        sleep $EXECDELAY
        /usr/local/bin/firewall/fw-main.sh
        ;;
        
    stop)
 
        ### RESET RULES, CHAINS, COUNTERS
        # Flush all rules
        $IPTABLES -F
        $IPTABLES -t nat -F
        $IPTABLES -t mangle -F
         
        # Remove all custom chains
        $IPTABLES -X
        $IPTABLES -t nat -X
        $IPTABLES -t mangle -X
         
        # zero all packet and byte counters 
        $IPTABLES -Z
        $IPTABLES -t nat -Z
        $IPTABLES -t mangle -Z

        ## And reset default policies
        $IPTABLES -P INPUT ACCEPT
        $IPTABLES -P OUTPUT ACCEPT
        $IPTABLES -P FORWARD ACCEPT
        
        echo "Warning: firewall stopped - all rules purged!"
        ;;

    status)
        echo "###############################################################"
        echo "##"
        echo "## FIREWALL CONFIGURATION"
        echo "##"
        echo "###############################################################"
        $IPTABLES -L -vn
        ;;

    about)
        echo "###############################################################"
        echo "##"
        echo "## Webserver firewall script (c) by Torsten Mueller"
        echo "##"
        echo "###############################################################"
        ;;
        
    restart|reload|force-reload)
        $0 stop
        sleep 1
        echo "Reloading all firewall rules..."
        $0 start
        ;;

      *)
        echo "$1: Command not found"
        echo "Please use: $0 {start|stop|restart|status|about}"
        exit 1
        ;;
    esac